require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Leiturinha_1' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'react-native-voice', :path => '../node_modules/@react-native-community/voice'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'Leiturinha_1Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end